# -*- coding: utf-8 -*-
"""cluster_profiling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13TE3IGtqo6zR20JWOL6ALBlaOPfyJogV
"""

# Mount google drive
from google.colab import drive
drive.mount('/content/drive')

"""#Cluster profiling based on pca and kmeans analysis"""

import numpy as np
import pandas as pd

directory = "/content/drive/MyDrive/Travel tide project"

# List files in the directory to verify filename
!ls "{directory}"

df_user = pd.read_csv(f'{directory}/user_base.csv')
df_segment = pd.read_csv(f'{directory}/user_segment.csv') # Corrected filename

df = pd.merge(df_user, df_segment, on='user_id')
print(df.shape)
print(df.dtypes)

df_user.groupby('gender').size()

#  we remove features that we dont analyze
columns=["user_id"]
# Check if 'user_id' column exists before dropping
if "user_id" in df.columns:
    df.drop(columns=columns, inplace=True)

# change booleans to int  -> good to build the heatmaps

# convert binary categoricals
df["gender"] = df["gender"].map({"F": 0, "M": 1, "O":2})
df["married"] = df["married"].astype(int)
df["has_children"] = df["has_children"].astype(int)

df["home_country"] = (df["home_country"] == 'canada').astype(int)

df.head().round(2)

# group= cluster
df.groupby('group').size()

# Create a temporary DataFrame with original gender values for crosstabulation
temp_df = pd.merge(df_user, df_segment, on='user_id')

print("Crosstabulation using original 'gender' values:")
original_gender_crosstab = pd.crosstab(temp_df["group"], temp_df["gender"])
display(original_gender_crosstab)

# Create a temporary DataFrame with original gender and having children values for crosstabulation
pd.crosstab(temp_df["group"],[temp_df["gender"],temp_df["has_children"]])

# Median values of all numeric features per group
group_summary = df.groupby("group").median(numeric_only=True).T.round(2)
print(df.groupby("group").size().reset_index())
group_summary

# Mean values of all numeric features per group
group_summary_mean = df.groupby("group").mean(numeric_only=True).T.round(2)
group_summary_mean

#box plots
import matplotlib.pyplot as plt
import seaborn as sns

# Example: distribution of money spent by group
sns.boxplot(x="group", y="avg_money_spent_per_hotel", data=df)
plt.show()

# Example: average km flown by group
sns.boxplot(x="group", y="avg_flight_km", data=df)
plt.show()

# box plots canceled trips and empty sessions per groups
import matplotlib.pyplot as plt
import seaborn as sns

selected_features = [
    "num_canceled_trips",
    "num_empty_sessions",
]

for feature in selected_features:
    plt.figure(figsize=(10, 5))
    sns.boxenplot(x="group", y=feature, data=df)
    plt.title(f"Boxenplot of {feature} by Cluster")
    plt.show()

# Heatmap of group means
import matplotlib.pyplot as plt
import seaborn as sns
group_summary = df.groupby("group").median(numeric_only=True).T.round(2)
plt.figure(figsize=(12, 6))
sns.heatmap(group_summary, cmap="coolwarm", annot=True, fmt=".1f")
plt.title("Feature Medians per Group")
plt.show()

#df.groupby("group").mean().T

# Heatmap of group means
group_summary_mean = df.groupby("group").mean(numeric_only=True).T
plt.figure(figsize=(12, 6))
sns.heatmap(group_summary_mean, cmap="coolwarm", annot=True, fmt=".1f")
plt.title("Feature Means per Group")
plt.show()

"""These two heatmaps together describe the **behavioral profiles of each cluster** and confirm that the clusters differ mainly in *engagement level, travel intensity, and spending power*. **Group 3** clearly stands out as the **most active and valuable segment**: it has the highest number of sessions, clicks, flights, and rooms, along with the highest average spend per flight and per hotel. **Group 4** shows similarly high engagement and strong spending, but slightly below Group 3, suggesting another high-value segment with somewhat less intensity. In contrast, **Group 1 consistently has the lowest values** across sessions, clicks, flights, rooms, and spending, identifying it as a low-engagement, low-activity group. Groups 0 and 2 fall between these extremes, with moderate engagement and travel frequency.

A second important pattern is that **spending per kilometer and hotel costs vary substantially across clusters**, with Group 0 showing unusually high average/median money per km, indicating a niche segment that tends to purchase more expensive trips despite only moderate activity. The similarity between mean and median patterns suggests the clusters are relatively stable and not driven by extreme outliers, although higher means than medians for some monetary features imply a few heavy spenders within certain groups. Overall, the clusters can be summarized as: Group 1 = minimal users, Group 0 = moderate users with premium trip characteristics, Group 2 = average travelers, Group 4 = high-engagement travelers, and Group 3 = power users / frequent high spenders. These profiles provide a strong foundation for targeted marketing, personalization, and differentiated product offerings.

#### Perk Assignments to Clusters

| Cluster | Data-Driven Summary                                                                                                                                                                                                                                                                                                                                   | Assigned Perk              | Justification                                                                                                                                                                                                                                                                                                                                                                                               |
| :------ | :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :------------------------- | :---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| **0**   | Younger, hotel-focused, high hotel spenders with low overall travel engagement, taking fewer but more luxurious or longer hotel-centric trips. Low flight activity.                                                                                                                                                                               | **Free hotel night with flight** | While they are hotel-focused, a "free hotel night with flight" could incentivize them to combine their hotel stays with flights, potentially increasing their overall engagement and flight activity. This is a compromise from the ideal "Premium Hotel Upgrades" due to the limited options provided.                                                  |
| **1**   | Highly engaged, frequent travelers who actively seek and use discounts, often bundling their travel. Likely to be older and travel year-round, with high session counts, clicks, and usage of flight/hotel discounts.                                                                                                                               | **Exclusive discount**     | This cluster already shows high engagement and actively seeks discounts. Exclusive discounts would directly reward their behavior and encourage continued high activity and loyalty. This aligns perfectly with their discount-seeking nature.                                                                                                 |
| **2**   | Efficient and active travelers, similar to Cluster 1 but with less emphasis on discounts and lower hotel spending. Value bundled services, with moderate engagement, flights, and hotels.                                                                                                                                                          | **Free meal**              | This cluster is efficient and active. A free meal can add perceived value and convenience to their trips without directly focusing on discounts or large financial incentives. It's a simple, tangible benefit that enhances their travel experience, especially if they are looking for efficiency.                                                     |
| **3**   | High-spending, often family or group travelers, taking long-haul flights, booking significantly in advance, and less interested in hotels as a primary focus. Highest `avg_money_spent_per_flight`, `avg_flight_km`, `avg_bags`, `avg_rooms`, `avg_seats`, `num_fam_and_fri_trips`, and `avg_time_after_booking`.                                                  | **Free checked bag**       | This cluster takes long-haul flights and often travels with family/friends (`num_fam_and_fri_trips`, `avg_bags`, `avg_seats` are high). A free checked bag directly addresses a practical need and cost associated with their travel style, providing significant value for group or long-distance trips.                                               |
| **4**   | Highly engaged users who spend a lot of time browsing and exploring options, possibly looking for shorter stays, and often interested in bundled deals. Highest `avg_clicks_per_session` and `avg_session_duration`. High `bundle_index`, `hotel_hunter_index`, and `flight_fanatic_index`, but lower `avg_night`. | **Free cancellation fee**  | This cluster is highly engaged in browsing and exploration, suggesting they might be indecisive or frequently changing plans. A "free cancellation fee" perk offers flexibility and reduces booking friction, encouraging them to book more frequently knowing they have an option to change without penalty, fitting their exploratory nature. |
"""