name: Sync to Hugging Face hub
on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Install LFS and Fix Pointers
        run: |
          git lfs install
          git lfs track "data/processed/*.csv"
          git add .gitattributes
          # This line converts existing large files into LFS pointers
          git lfs migrate import --everything --include="*.csv"

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push --force "https://JAM14:$HF_TOKEN@huggingface.co/spaces/JAM14/travel_tide_perks" HEAD:refs/heads/main
